
=begin
Acesso.create! nome: 'Campana', status: 1, tipo: 0, email: 'campana@4cta.eb.mil.br', password: 'password'

Hierarq.create! nome: 'FC'
Hierarq.create! nome: 'Sd EV'
Hierarq.create! nome: 'Sd EP'
Hierarq.create! nome: 'Cb'
Hierarq.create! nome: '3º Sgt'
Hierarq.create! nome: '2º Sgt'
Hierarq.create! nome: '1º Sgt'
Hierarq.create! nome: 'ST'
Hierarq.create! nome: 'Asp Of'
Hierarq.create! nome: '2º Ten'
Hierarq.create! nome: '1º Ten'
Hierarq.create! nome: 'Cap'
Hierarq.create! nome: 'Maj'
Hierarq.create! nome: 'TC'
Hierarq.create! nome: 'Cel'
Hierarq.create! nome: 'Gen Bda'
Hierarq.create! nome: 'Gen Div'
Hierarq.create! nome: 'Gen Ex'
Hierarq.create! nome: 'Mal'

Cidade.create! nome: 'Assis Brasil - AC'
Cidade.create! nome: 'Auaris - RR'
Cidade.create! nome: 'Barcelos'
Cidade.create! nome: 'Boa Vista - RR'
Cidade.create! nome: 'Bomfim - RR'
Cidade.create! nome: 'Cruzeiro do Sul - AC'
Cidade.create! nome: 'Cucuí - AM'
Cidade.create! nome: 'Epitacolandia - AC'
Cidade.create! nome: 'Estirão do Equador - AM'
Cidade.create! nome: 'Guajará Mirin - RO'
Cidade.create! nome: 'Humaitá - AM'
Cidade.create! nome: 'Ipiranga - AM'
Cidade.create! nome: 'Maturacá - AM'
Cidade.create! nome: 'Marechal Thaumaturgo - AC'
Cidade.create! nome: 'Manaus - AM'
Cidade.create! nome: 'Manicoré - AM'
Cidade.create! nome: 'Normandia - RR'
Cidade.create! nome: 'Pacaraima - RR'
Cidade.create! nome: 'Palmeira do Javari - AM'
Cidade.create! nome: 'Pari-cachoera - AM'
Cidade.create! nome: 'Plácido de Castro - AC'
Cidade.create! nome: 'Porto Velho - RR'
Cidade.create! nome: 'Principe da Beira - RO'
Cidade.create! nome: 'Querari - AM'
Cidade.create! nome: 'Rio Branco - AC'
Cidade.create! nome: 'Santa Rosa da Cachoeira - AM'
Cidade.create! nome: 'São Gabriel da Cachoeira - AM'
Cidade.create! nome: 'São joaquim - AM'
Cidade.create! nome: 'São Salvador - AC'
Cidade.create! nome: 'Surucucu - RR'
Cidade.create! nome: 'Tabatinga- AM'
Cidade.create! nome: 'Tefé - AM'
Cidade.create! nome: 'Tunuí - AM'
Cidade.create! nome: 'Uiramutã - RR'
Cidade.create! nome: 'Vila Bitencourt - AM'
Cidade.create! nome: 'Vilhena - RO'
Cidade.create! nome: 'Yauaretê - AM'

Idioma.create! nome: 'Inglês: consegue ler frases básicas, como manuais de instrução'
Idioma.create! nome: 'Inglês: consegue ler textos curtos, como em websites'
Idioma.create! nome: 'Inglês: consegue ler um livro'
Idioma.create! nome: 'Inglês: consegue compreender diálogos simples'
Idioma.create! nome: 'Inglês: consegue compreender qualquer diálogo'
Idioma.create! nome: 'Inglês: consegue falar frases básicas'
Idioma.create! nome: 'Inglês: consegue travar um diálogo'
Idioma.create! nome: 'Inglês: consegue escrever frases curtas'
Idioma.create! nome: 'Inglês: consegue escrever artigos longos'
Idioma.create! nome: 'Espanhol: consegue ler frases básicas, como manuais de instrução'
Idioma.create! nome: 'Espanhol: consegue ler textos curtos, como em websites'
Idioma.create! nome: 'Espanhol: consegue ler um livro'
Idioma.create! nome: 'Espanhol: consegue compreender diálogos simples'
Idioma.create! nome: 'Espanhol: consegue compreender qualquer diálogo'
Idioma.create! nome: 'Espanhol: consegue falar frases básicas'
Idioma.create! nome: 'Espanhol: consegue travar um diálogo'
Idioma.create! nome: 'Espanhol: consegue escrever frases curtas'
Idioma.create! nome: 'Espanhol: consegue escrever artigos longos'
=end
#=begin
Cargo.create! nome: 'Ch CT/CTA'
Cargo.create! nome: 'SCh CT/CTA'
Cargo.create! nome: 'Ch Seç de Planejamento e Controle'
Cargo.create! nome: 'Adj Seç de Planejamento e Controle'
Cargo.create! nome: 'Aux Seç de Planejamento e Controle'
Cargo.create! nome: 'Ch Div Técnica'
Cargo.create! nome: 'Ch Seç Gerência - DT'
Cargo.create! nome: 'Adj Seç Gerência -  DT'
Cargo.create! nome: 'Aux Seç Gerência - DT'
Cargo.create! nome: 'Ch Seç Projetos - DT'
Cargo.create! nome: 'Adj Seç Projetos - DT'
Cargo.create! nome: 'Aux Seç Projetos - DT'
Cargo.create! nome: 'Ch Seç Logística - DT'
Cargo.create! nome: 'Adj Seç Logística - DT'
Cargo.create! nome: 'Aux Seç Logística - DT'
Cargo.create! nome: 'Ch Seç Capacitação - DT'
Cargo.create! nome: 'Adj Seç Capacitação - DT'
Cargo.create! nome: 'Aux Seç Capacitação - DT'
Cargo.create! nome: 'Ch Div Operacional'
Cargo.create! nome: 'Ch Central de Serviços - DO'
Cargo.create! nome: 'Adj Central de Serviços - DO'
Cargo.create! nome: 'Aux Central de Serviços - DO'
Cargo.create! nome: 'Ch Seç Gerenciamento das operações - DO'
Cargo.create! nome: 'Adj Seç Gerenciamento das operações - DO'
Cargo.create! nome: 'Aux Seç Gerenciamento das operações - DO'
Cargo.create! nome: 'Ch SubSeç de Controle Operacional - DO'
Cargo.create! nome: 'Adj SubSeç de Controle Operacional - DO'
Cargo.create! nome: 'Aux SubSeç de Controle Operacional - DO'
Cargo.create! nome: 'Ch Seç Gerenciamento Técnico - DO'
Cargo.create! nome: 'Adj Seç Gerenciamento Técnico - DO'
Cargo.create! nome: 'Aux Seç Gerenciamento Técnico - DO'
Cargo.create! nome: 'Ch Subseç Gerenciamento de Infraestrutura - DO'
Cargo.create! nome: 'Adj Subseç Gerenciamento de Infraestrutura - DO'
Cargo.create! nome: 'Aux Subseç Gerenciamento de Infraestrutura - DO'
Cargo.create! nome: 'Ch Seç Rede Rádio - DO'
Cargo.create! nome: 'Adj Seç Rede Rádio - DO'
Cargo.create! nome: 'Aux Seç Rede Rádio - DO'
Cargo.create! nome: 'Ch Seç Segurança da Informação - STIR'
Cargo.create! nome: 'Adj Seç Segurança da Informação - STIR'
Cargo.create! nome: 'Aux Seç Segurança da Informação - STIR'
Cargo.create! nome: 'Ch Div de Apoio'
Cargo.create! nome: 'Ch Seç Pessoal'
Cargo.create! nome: 'Adj Seç Pessoal'
Cargo.create! nome: 'Aux Seç Pessoal'
Cargo.create! nome: 'Ch Secretaria'
Cargo.create! nome: 'Adj Secretaria'
Cargo.create! nome: 'Aux Secretaria'
Cargo.create! nome: 'Ch Seç de Instrução'
Cargo.create! nome: 'Adj Seç de Instrução'
Cargo.create! nome: 'Aux Seç de Instrução'
Cargo.create! nome: 'Ch Seç de Comunicação Social'
Cargo.create! nome: 'Adj Seç de Comunicação Social'
Cargo.create! nome: 'Aux Seç de Comunicação Social'
Cargo.create! nome: 'Ch Seç de Inteligência'
Cargo.create! nome: 'Adj Seç de Inteligência'
Cargo.create! nome: 'Aux Seç de Inteligência'
Cargo.create! nome: 'Ch Contigente'
Cargo.create! nome: 'Adj Contigente'
Cargo.create! nome: 'Aux Contigente'
Cargo.create! nome: 'Ch Seç de Informática - DAP'
Cargo.create! nome: 'Adj Seç de Informática - DAP'
Cargo.create! nome: 'Aux Seç de Informática - DAP'
Cargo.create! nome: 'Ch Div Administrativa'
Cargo.create! nome: 'Ch Seç Licitações e Contrato'
Cargo.create! nome: 'Adj Seç Licitações e Contrato'
Cargo.create! nome: 'Aux Seç Licitações e Contrato'
Cargo.create! nome: 'Ch Seç Controle de Material e Patrimônio'
Cargo.create! nome: 'Adj Seç Controle de Material e Patrimônio'
Cargo.create! nome: 'Aux Seç Controle de Material e Patrimônio'
Cargo.create! nome: 'Ch Seç Armazenagem Triagem e Suprimento'
Cargo.create! nome: 'Adj Seç Armazenagem Triagem e Suprimento'
Cargo.create! nome: 'Aux Seç Armazenagem Triagem e Suprimento'
Cargo.create! nome: 'Ch Reserva de Material'
Cargo.create! nome: 'Adj Reserva de Material'
Cargo.create! nome: 'Aux Reserva de Material'
Cargo.create! nome: 'Ch Seç de Serviços Gerais'
Cargo.create! nome: 'Adj Seç de Serviços Gerais'
Cargo.create! nome: 'Aux Seç de Serviços Gerais'
Cargo.create! nome: 'Ch Seç de Manutenção e Transporte'
Cargo.create! nome: 'Adj Seç de Manutenção e Transporte'
Cargo.create! nome: 'Aux Seç de Manutenção e Transporte'
#=end
=begin
Habilidade.create! nome: 'Administração de Base de Dados'
Habilidade.create! nome: 'Administração de Rede Rádio'
Habilidade.create! nome: 'Administração de Rede Telefônica VoIP'
Habilidade.create! nome: 'Administração de Redes'
Habilidade.create! nome: 'Administração de Sistemas Linux: Redes e Segurança'
Habilidade.create! nome: 'Administração de Sistemas Linux: Serviços para Internet'
Habilidade.create! nome: 'Administração de Videoconferência'
Habilidade.create! nome: 'Administração/Operação de redes'
Habilidade.create! nome: 'Análise de Sistemas'
Habilidade.create! nome: 'Arquitetura de redes: desenho, projeto, implantação e entrega'
Habilidade.create! nome: 'Arquitetura e Protocolos de Rede TCP-IP'
Habilidade.create! nome: 'Asterisk'
Habilidade.create! nome: 'Big Data e Análise de dados'
Habilidade.create! nome: 'BGP Avançado'
Habilidade.create! nome: 'Cabeamento Estruturado'
Habilidade.create! nome: 'CAD'
Habilidade.create! nome: 'Ciência de Dados'
Habilidade.create! nome: 'Dados e Armazenamento'
Habilidade.create! nome: 'Django'
Habilidade.create! nome: 'Desenvolvimento de SW - Aplicações Web'
Habilidade.create! nome: 'Desenvolvimento de SW - Frameworks e Aplicações Corporativas'
Habilidade.create! nome: 'Desenvolvimento de SW -  Interfaces Gráficas e Bancos de Dados'
Habilidade.create! nome: 'Elaboração de PDTI'
Habilidade.create! nome: 'Engenharia Reversa de Código Malicioso'
Habilidade.create! nome: 'Formação em Segurança Cibernética'
Habilidade.create! nome: 'Fundamentos de Desenvolvimento de SW'
Habilidade.create! nome: 'Fundamentos de Governança de TI'
Habilidade.create! nome: 'Fundamentos de IoT'
Habilidade.create! nome: 'Gerenciamento de Serviços de TI'
Habilidade.create! nome: 'Gestão Estratégica Organizacional'
Habilidade.create! nome: 'Gestão de Riscos de TI com NBR 31000 e NBR 27005'
Habilidade.create! nome: 'Gestão de Segurança da Informação com NBR 27001 e NBR 27002'
Habilidade.create! nome: 'Gerenciamento de Projetos de TI'
Habilidade.create! nome: 'Governança de TI com COBIT'
Habilidade.create! nome: 'Hardening em Linux'
Habilidade.create! nome: 'Implantação e Administração de Firewall'
Habilidade.create! nome: 'Implantação e Administração de Proxy'
Habilidade.create! nome: 'Infraestrutura de Instalações'
Habilidade.create! nome: 'Infraestrutura de Rede Rádio'
Habilidade.create! nome: 'Infraestrutura de Telefonia VoIP'
Habilidade.create! nome: 'Instalador de Cabeamento Estruturado'
Habilidade.create! nome: 'Instalador de Cabos em Posteamento'
Habilidade.create! nome: 'Introdução ao Linux'
Habilidade.create! nome: 'IPv6 Básico'
Habilidade.create! nome: 'Java'
Habilidade.create! nome: 'Javascript'
Habilidade.create! nome: 'LAN'
Habilidade.create! nome: 'MAN'
Habilidade.create! nome: 'MySQL'
Habilidade.create! nome: 'Modelagem de Banco de Dados'
Habilidade.create! nome: 'Monitoração de Redes'
Habilidade.create! nome: 'MPLS'
Habilidade.create! nome: 'OSPF Avançado'
Habilidade.create! nome: 'Perícia Forense'
Habilidade.create! nome: 'Planejamento e Contratação de Serviços de TI'
Habilidade.create! nome: 'Planejamento e Gestão Estratégica de TI'
Habilidade.create! nome: 'Planejamento e Projeto de Infraestrutura de Datacenter'
Habilidade.create! nome: 'Python'
Habilidade.create! nome: 'PostgreSQL'
Habilidade.create! nome: 'Ruby on Rails'
Habilidade.create! nome: 'Segurança em Redes sem Fio'
Habilidade.create! nome: 'Seleção de Fornecedores de TI'
Habilidade.create! nome: 'Servidores'
Habilidade.create! nome: 'Suporte ao Cliente'
Habilidade.create! nome: 'Telefonia VoIP'
Habilidade.create! nome: 'Teste de Invasão de Aplicações Web'
Habilidade.create! nome: 'Tratamento de Incidentes de Segurança'
Habilidade.create! nome: 'Virtualização de Servidores'
Habilidade.create! nome: 'WAN'
Habilidade.create! nome: 'WLAN'
Habilidade.create! nome: 'VoIP'

FormacaoAcad.create! nome: 'Ensino Básico Completo'
FormacaoAcad.create! nome: 'Ensino Fundamental Completo'
FormacaoAcad.create! nome: 'Ensino Médio Completo'
FormacaoAcad.create! nome: 'Licenciatura e Bacharelado em Educação Física'
FormacaoAcad.create! nome: 'Bacharelado em Enfermagem'
FormacaoAcad.create! nome: 'Bacharelado em Fisioterapia'
FormacaoAcad.create! nome: 'Bacharelado em Veterinária'
FormacaoAcad.create! nome: 'Bacharelado em Odontologia'
FormacaoAcad.create! nome: 'Bacharelado em Ciência da Computação'
FormacaoAcad.create! nome: 'Bacharelado em Engenharia Civil'
FormacaoAcad.create! nome: 'Bacharelado em Engenharia da Computação'
FormacaoAcad.create! nome: 'Bacharelado em Engenharia da Comunicações'
FormacaoAcad.create! nome: 'Bacharelado em Engenharia Eletrônica'
FormacaoAcad.create! nome: 'Bacharelado em Engenharia Elétrica'
FormacaoAcad.create! nome: 'Bacharelado em Sistemas de Informação'
FormacaoAcad.create! nome: 'Bacharelado em Administração'
FormacaoAcad.create! nome: 'Bacharelado em Ciências Contábeis'
FormacaoAcad.create! nome: 'Bacharelado em Direito'
FormacaoAcad.create! nome: 'Bacharelado em Comunicação Social'
FormacaoAcad.create! nome: 'Bacharelado em Psicologia'
FormacaoAcad.create! nome: 'Bacharelado em Serviço Social'
FormacaoAcad.create! nome: 'Tecnológico em Radiologia'
FormacaoAcad.create! nome: 'Tecnológico em Gestão de Recursos Humanos'
FormacaoAcad.create! nome: 'Tecnológico em Logística'
FormacaoAcad.create! nome: 'Tecnológico em Segurança do Trabalho'
FormacaoAcad.create! nome: 'Tecnológico em Gastronomia'
FormacaoAcad.create! nome: 'Tecnológico em Redes de Computadores'
FormacaoAcad.create! nome: 'Tecnológico em Tecnologia da Informação'
FormacaoAcad.create! nome: 'Técnico em Eletrônica'
FormacaoAcad.create! nome: 'Técnico em Eletrotécnica'
FormacaoAcad.create! nome: 'Técnico em Informática'
FormacaoAcad.create! nome: 'Técnico em Mecânica'
FormacaoAcad.create! nome: 'Técnico em Mecatrônica'
FormacaoAcad.create! nome: 'Técnico em Refrigeração e Climatização'
FormacaoAcad.create! nome: 'Técnico em Administração'
FormacaoAcad.create! nome: 'Técnico em Edificações'
FormacaoAcad.create! nome: 'Técnico em Enfermagem'
FormacaoAcad.create! nome: 'Técnico em Geoprocessamento'
FormacaoAcad.create! nome: 'Técnico em Finanças'
FormacaoAcad.create! nome: 'Técnico em Prótese Dentária'
FormacaoAcad.create! nome: 'Técnico em Radiologia'
FormacaoAcad.create! nome: 'Técnico em Secretariado'
FormacaoAcad.create! nome: 'Técnico em Transporte de Cargas'
FormacaoAcad.create! nome: 'Técnico em Construção Civil'

FormacaoMil.create! nome: 'IIQ - Com'
FormacaoMil.create! nome: 'CFC - Com'
FormacaoMil.create! nome: 'CFST - STT'
FormacaoMil.create! nome: 'CFOT - OTT'
FormacaoMil.create! nome: 'EsSA - Com'
FormacaoMil.create! nome: 'EsFCEx - QCO - Informática'
FormacaoMil.create! nome: 'EsFCEx - QCO - Administração'
FormacaoMil.create! nome: 'EsLog - Mnt Com'
FormacaoMil.create! nome: 'EsLog - Int'
FormacaoMil.create! nome: 'AMAN - Com'
FormacaoMil.create! nome: 'IME - Com'
FormacaoMil.create! nome: 'IME - Comp'

CertTi.create! nome: 'CCNA Routing & Switching'
CertTi.create! nome: 'CCSI'
CertTi.create! nome: 'Data Cabling System'
CertTi.create! nome: 'FCP Professional'
CertTi.create! nome: 'FCP FO'
CertTi.create! nome: 'FCP Master'
CertTi.create! nome: 'FTTx Equipamentos'
CertTi.create! nome: 'ITIL Foundation'
CertTi.create! nome: 'ITIL Practitioner'
CertTi.create! nome: 'ITIL Intermediate'
CertTi.create! nome: 'ITIL Expert'
CertTi.create! nome: 'ITIL Master'
CertTi.create! nome: 'PMP - Project Manager Professional'
CertTi.create! nome: 'Prince2 Foundation'
CertTi.create! nome: 'Prince2 Pratictioner'

Encargo.create! nome: 'Of TFM'
Encargo.create! nome: 'Of Tiro'
Encargo.create! nome: 'Of Segurança na Instrução'
Encargo.create! nome: 'Sgt Tiro'

Servico.create! nome: 'Acesso à EBNet'
Servico.create! nome: 'pacotes_servico à Internet'
Servico.create! nome: 'Correio Eletrônico Regional'
Servico.create! nome: 'Relay de Correio'
Servico.create! nome: 'Consultoria Técnica'
Servico.create! nome: 'Apoio ao Fornecimento de Imagens de Segurança Pública'
Servico.create! nome: 'Virtual Private Network (VPN)'
Servico.create! nome: 'Hospedagem de Sistemas Regionais'
Servico.create! nome: 'Conexão ao SIAFI'
Servico.create! nome: 'Videoconferência'
Servico.create! nome: 'Hospedagem de Páginas de Internet'
Servico.create! nome: 'Acesso à Telefonia Corporativa'
Servico.create! nome: 'Suporte aos Sistemas do Exército'
Servico.create! nome: 'Perícia Computacional'
Servico.create! nome: 'Transmissão de Radiograma'
Servico.create! nome: 'Módulo de Proteção Cibernética'

Parado.create! nome: 'Serviço de EBNet Lote 1'
Parado.create! nome: 'Serviço de EBNet Lote 2'
Parado.create! nome: 'Serviço de Hospedagem de páginas web'
Parado.create! nome: 'Serviço de Hospedagem de sistemas regionais'
Parado.create! nome: 'Serviço de Correio eletrônico regional'
Parado.create! nome: 'Serviço de Telefonia corporativa'
Parado.create! nome: 'Sistema elétrico do DC'
Parado.create! nome: 'Sistema de climatização do DC'
Parado.create! nome: 'Sistema de telecom do DC'
Parado.create! nome: 'Backbone Datacenter do CTA-MAN'
Parado.create! nome: 'Roteador Lote 1 de PP'
Parado.create! nome: 'Roteador de integração de PP'
Parado.create! nome: 'Roteador Lote 2 de PP'
Parado.create! nome: 'Switch da MAN'
Parado.create! nome: 'Servidor'
Parado.create! nome: 'Storage'
Parado.create! nome: 'Central telefônica'
Parado.create! nome: 'Firewall'
Parado.create! nome: 'Roteador de integração do PP do CTA'
Parado.create! nome: 'Roteador Lote 1 PP do CTA'
Parado.create! nome: 'Roteador Lote 2 PP do CTA'
Parado.create! nome: 'Switch core do CTA'
Parado.create! nome: 'Gerador'
Parado.create! nome: 'UPS'
Parado.create! nome: 'Subestação'
Parado.create! nome: 'Quadro Elétrico'
Parado.create! nome: 'Cabeamento de acesso à rede externa'
Parado.create! nome: 'Cabeamento de backbone do DC'
Parado.create! nome: 'Cabeamento horizontal do DC'
Parado.create! nome: 'Switch do DC'
Parado.create! nome: 'Indeterminado'

Motivo.create! nome: 'Desalinhamento de antena satelital em PP'
Motivo.create! nome: 'Rompimento de cabo óptico em MAN'
Motivo.create! nome: 'Downtime de VMs'
Motivo.create! nome: 'Desconfiguração de VMs'
Motivo.create! nome: 'Desconfiguração de central telefônica'
Motivo.create! nome: 'Incêndio em DC'
Motivo.create! nome: 'Desconfiguração no chaveamento rede elétrica-gerador'
Motivo.create! nome: 'Banco de baterias do UPS não suporta carga'
Motivo.create! nome: 'Rompimento no cabeamento estruturado do DC'
Motivo.create! nome: 'Desconfiguração do roteador no DC'
Motivo.create! nome: 'Desconfiguração de switch em MAN'
Motivo.create! nome: 'Perda de banco de dados de servidor'
Motivo.create! nome: 'Queima de componente de HW'
Motivo.create! nome: 'Vírus em componente de SW'
Motivo.create! nome: 'Falha de segurança no DC'
Motivo.create! nome: 'Falta de combustível no gerador'
Motivo.create! nome: 'Pane mecânica no gerador'
Motivo.create! nome: 'Pane elétrica no gerador'
Motivo.create! nome: 'Desconfiguração do UPS'
Motivo.create! nome: 'Falta de gás nos climatizadores'
Motivo.create! nome: 'Desconfiguração nos climatizadores'
Motivo.create! nome: 'Queima de componente eletrônico nos climatizadores'
Motivo.create! nome: 'Queda de poste em MAN'
Motivo.create! nome: 'Desabastecimento de concessionária de energia'
Motivo.create! nome: 'Desconfiguração de proxy'
Motivo.create! nome: 'Desconfiguração de firewall'
Motivo.create! nome: 'Desconfiguração de gateway'
Motivo.create! nome: 'Superaquecimento de componente eletrônico'
Motivo.create! nome: 'Superaquecimento de HW'
Motivo.create! nome: 'Switch do DC'
Motivo.create! nome: 'Indeterminado'
=end

#sdsdsds
